### PR TITLE
Created install Checks for installation:

### PR DESCRIPTION
**Pull request by saintphaenixos**
Created basic installation checks for installed programs, as well as what version of java is installed on the target install computer.

This should give some more feedback to the user who is installing this app if they do or don't have some of the requested command line programs installed: `grep, java 17 or above, xclip, pgrep, pkexec, whereis`. 

If this is to your liking, I can similarly copy the work over to the Install.sh for compiling.

### CODE REVIEW

**Comment by omegaui** [comment]
Hello!

Thanks a lot for your contribution.
I very much appreciate your help.
Also, It would be very nice of you if you do the same for the other install.sh script.
Then, I'll merge this pull request.

Thank You.

**Comment by saintphaenixos** [comment]
> Hello!
> 
> Thanks a lot for your contribution. I very much appreciate your help. Also, It would be very nice of you if you do the same for the other install.sh script. Then, I'll merge this pull request.
> 
> Thank You.

No worries, I know no Dart, but I'm happy to help with Bash Scripting which I know enough to be dangerous in.

I've added the variation for the compilation installation, as well as the normal installation.

I also cleaned up the code a bit, I didn't realize that it was that messy.

**Comment by omegaui** [comment]
Thanks a lot.
I do not know bash scripting so much so that why it was messy.

**Comment by saintphaenixos** [comment]
> Thanks a lot. I do not know bash scripting so much so that why it was messy.

As an aside, you are fine, the code is simple, but it works. :smile: I was talking more about cleaning up my code.

**Pull request merged**
